sudo: false
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --no-dev

script:
  - vendor/bin/phpunit tests
