env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

sudo: false
language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - phpunit tests
  - vendor/bin/codecept run unit --coverage --coverage-xml

after_script:
  - mv tests/_output/coverage.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --id 12345 --exit-code $TRAVIS_TEST_RESULT
