sudo: false
language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - phpunit --bootstrap ./vendor/autoload.php tests
